; --------------------------------------------------
;       KEEP CODING AND NOBODY EXPLODES (KCANE)
; --------------------------------------------------
; Project for 66.09.Laboratorio de Microcomputadoras
; Faculty of Engineering, University of Buenos Aires
;
; By Ana Czarnitzki, Alejandro García & Juan Fresia
;
; --------------------------------------------------
;
; --------------------------------------------------
;               TFT COLOR DEFINITIONS
; --------------------------------------------------
	.EQU MAGENTA, 0xF8F8
	.EQU ORANGE, 0xE4E4
	.EQU BLACK, 0x0000
	.EQU WHITE, 0xFFFF
	.EQU BLUE_LIGHT, 0x1D1D
	.EQU BLUE_DARK, 0x1818
	.EQU RED_LIGHT, 0xE0E0
	.EQU RED_DARK, 0xC0C0
	.EQU GREEN_LIGHT, 0x4747
	.EQU GREEN_DARK, 0x6666
